import type { ComexFieldDefInput } from '../../types/comex';

/**
 * Catálogo inicial de campos — gravado em comex_field_defs na primeira abertura.
 * Depois disso o CRUD de metadado no M18 é a fonte da verdade (nada no DDL).
 */
export const DEFAULT_COMEX_FIELD_DEFS: ComexFieldDefInput[] = [
  {
    entity: 'process',
    field_key: 'type',
    label: 'Tipo',
    data_type: 'enum',
    widget: 'select',
    required: true,
    ui_list: true,
    ui_form: true,
    sort_order: 10,
    enum_options: [
      { value: 'importacao', label: 'Importação (DUIMP)' },
      { value: 'exportacao', label: 'Exportação (DU-E)' },
    ],
  },
  {
    entity: 'process',
    field_key: 'client_name',
    label: 'Cliente / importador',
    data_type: 'text',
    widget: 'client',
    ui_list: true,
    ui_form: true,
    sort_order: 20,
  },
  {
    entity: 'process',
    field_key: 'bl_number',
    label: 'BL',
    data_type: 'text',
    widget: 'select',
    ui_list: true,
    ui_form: true,
    sort_order: 30,
  },
  {
    entity: 'process',
    field_key: 'declaration_number',
    label: 'Nº DUIMP / DU-E',
    data_type: 'text',
    widget: 'select',
    ui_list: true,
    ui_form: true,
    consult_key: true,
    sort_order: 40,
  },
  {
    entity: 'process',
    field_key: 'duimp_version',
    label: 'Versão DUIMP',
    data_type: 'enum',
    widget: 'select',
    ui_form: true,
    sort_order: 45,
    enum_options: Array.from({ length: 10 }, (_, i) => {
      const n = String(i + 1);
      return { value: n, label: `Versão ${n}` };
    }),
  },
  {
    entity: 'process',
    field_key: 'ncm_code',
    label: 'NCM',
    data_type: 'text',
    widget: 'ncm',
    ui_list: true,
    ui_form: true,
    sort_order: 50,
  },
  {
    entity: 'process',
    field_key: 'product_description',
    label: 'Descrição comercial',
    data_type: 'text',
    widget: 'textarea',
    ui_form: true,
    sort_order: 60,
  },
  {
    entity: 'process',
    field_key: 'incoterm',
    label: 'Incoterm',
    data_type: 'enum',
    widget: 'select',
    ui_form: true,
    sort_order: 70,
    enum_options: ['FOB', 'CIF', 'FCA', 'DDP', 'EXW'].map((value) => ({
      value,
      label: value,
    })),
  },
  {
    entity: 'process',
    field_key: 'port_of_origin_code',
    label: 'Porto origem',
    data_type: 'text',
    widget: 'port',
    ui_list: true,
    ui_form: true,
    sort_order: 80,
  },
  {
    entity: 'process',
    field_key: 'port_of_destination_code',
    label: 'Porto destino',
    data_type: 'text',
    widget: 'port',
    ui_form: true,
    sort_order: 90,
  },
  {
    entity: 'process',
    field_key: 'customs_house',
    label: 'Recinto / URF',
    data_type: 'text',
    widget: 'customs',
    ui_form: true,
    sort_order: 100,
  },
  {
    entity: 'process',
    field_key: 'fob_value_usd',
    label: 'FOB USD',
    data_type: 'number',
    widget: 'number',
    kpi: 'fob',
    ui_list: true,
    ui_form: true,
    sort_order: 110,
  },
  {
    entity: 'process',
    field_key: 'cif_value_brl',
    label: 'CIF BRL (pitch — não Ad Valorem)',
    data_type: 'number',
    widget: 'number',
    kpi: 'cif',
    ui_form: true,
    sort_order: 120,
  },
  {
    entity: 'process',
    field_key: 'status',
    label: 'Status operacional',
    data_type: 'enum',
    widget: 'select',
    ui_form: true,
    sort_order: 130,
    enum_options: [
      { value: 'documentos_indexados', label: 'Documentos indexados' },
      { value: 'aguardando_di', label: 'Aguardando DI / DUIMP' },
      { value: 'duimp_registrada', label: 'DUIMP registrada' },
      { value: 'due_emitida', label: 'DU-E emitida' },
      { value: 'conferencia', label: 'Conferência aduaneira' },
      { value: 'desembaracado', label: 'Desembaraçado' },
      { value: 'armazenado', label: 'Armazenado no hub' },
    ],
  },
  {
    entity: 'process',
    field_key: 'pucomex_status',
    label: 'Status Portal',
    data_type: 'enum',
    widget: 'select',
    ui_list: true,
    ui_form: true,
    sort_order: 140,
    enum_options: [
      { value: 'Aguardando declaração', label: 'Aguardando declaração' },
      { value: 'Consultado no Portal', label: 'Consultado no Portal' },
      { value: 'Integrado e Validador OK', label: 'Integrado e Validador OK' },
      { value: 'Falha na consulta', label: 'Falha na consulta' },
    ],
  },
  {
    entity: 'process',
    field_key: 'notes',
    label: 'Notas',
    data_type: 'text',
    widget: 'textarea',
    ui_form: true,
    sort_order: 150,
  },
];
